create table person(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fio varchar(100),
	email varchar(100),
	phone int
);

create table department(
	id int,
	description text
);

 create table pack (
 	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 	senderName varchar(60),
 	senderDepart varchar(60),
 	recipientDepart varchar(60),
 	recipientPhoneNumber int,
 	recipientName varchar(60),
 	status varchar(20),
 	dateCreation timestamp,
 	dateChange timestamp
 );

create table notification(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	notification text,
	status varchar(20)
);

select * from pack;
select * from person;
select * from notification;
select * from department;

drop table person ;
drop table pack ;
drop table notification;
drop table department;
